library(dplyr)
library(shiny)
library(shinyWidgets)
library(shinythemes)
library(leaflet)
library(plotly)
house_sales <- read.csv("data/house_sales.csv", stringsAsFactors = FALSE)
# The page one's house preference depends on the frequency of bedroom bathroom
# combination. The most popular 30 bathroom bedroom combinations.

home_page <- tabPanel(
  "Home", 
  fluidRow(
    column(width = 12, img(src="banner.jpg", style = "display: block; margin-left: auto; margin-right: auto; width: 100%;"))
  ),
  tags$h3("Welcome"),
  p("Wecome! We are thrilled to have you with us! At this page, we will guide 
    you through to explore our website. We are an independent, non-commercial 
  set of tools and data that allow you to explore the housing market in King
  County. We aim to help you understand how the specifications of a house affect 
the housing price and guide you to make better choices!"),
  tags$h3("About our Dataset"),
  p("Our target audience would be potential house buyers and renters. We focused
on the features that could have an impact on house sales prices. We draw data 
from the", a("House Sales in King County", 
href = "https://www.kaggle.com/harlfoxem/housesalesprediction"), "and the 
dataset contains the house sale prices for King County between May 2014 to May 
2015, it also contains 19 house features. It is generated by Harlfoxem from 
public record."),
  tags$h3("Getting Started"),
  p("Buying your first property is a major investment and can be a lucrative
    one, you could ask fundamental questions such as:"),
  p(em("- What is the price and condition in different areas around Seattle?")),
  p(em("- How many badrooms and bathrooms you want? And what is the price on 
       each configuration?")),
  p(em("- How does seasonality affect house value? For your house When is the 
  best time to buy/sell the house?")),
  tags$h3("Technical Stuff"),
  p("We used Shiny App to build interactive web app straight from R. We also 
    used serval R pacakages to help format the application and wrangle the 
    data: "),
  p("- dplyr: to solve the data manipulation challenge"),
  p("- leaflet: to build our interactive map "),
  p("- ggolot2: to help create elegant and complex plots"),
  p("- shinythemes: to alter the overall appearance of Our Shiny application"),
  tags$h3("Contact Us"),
  p("W'd love to hear from you. Whether you thave a question about feature, 
    price, or anything else, our team is ready to answer all your questions!"),
  p("Amara Perry: ", a("amaraperry9@gmail.com", href = "mailto:amaraperry9@gmail.com")),
  p("George Ma: ", a("zma9977@uw.edu", href = "mailto:zma9977@uw.edu")),
  p("Lufei Wang: ", a("lufeiw@uw.edu", href = "mailto:lufeiw@uw.edu")),
  p("Lyons Lu: ", a("lyons2000124@outlook.com", href = "mailto:lyons2000124@outlook.com")),
  p("Mengru Zhou: ", a("vickyzhou9119@outlook.com", href = "mailto:vickyzhou9119@outlook.com"))
)

page_one <- tabPanel(
  title = "Seattle House Map", 
  div(class="outer",tags$head(includeCSS("style.css")),
      leafletOutput("map", width = "100%", height = "100%"),
      absolutePanel(id = "controls", class = "panel panel-default", fixed = TRUE,
                    draggable = FALSE, top = 60, left = "auto", right = 20, 
                    bottom = "auto", width = "auto", height = "auto",
                    h3("Seattle Housing Sale History"),
                    p("Click on each data point to see more info"),
                    selectInput("color", "Color By:", c("Price" = "price",
                                                    "Condition" = "condition")),
                    selectInput("size", "Size By:", c("Don't show size" = "none",
                                "Area of Living Space" = "sqft_living", 
                                "Rating" = "grade"))
      )
  )
)

house_preference <- house_sales %>% 
  mutate(price_per_square = price / sqft_living) %>% 
  group_by(bedrooms, bathrooms) %>% 
  summarise(price_per_square = round(mean(price_per_square), digits = 1),
            n = n()) %>% 
  arrange(-n) %>% 
  head(n = 30)
unique_bedrooms <- sort(unique(house_preference$bedrooms))
unique_bathrooms <- sort(unique(house_preference$bathrooms))

page_two <- tabPanel(
  "Bedroom Selection",
  titlePanel("Bedroom Selection"),
  h5("How many bathrooms would be the best choice for you given 
     the type of house you prefer? In the selection box below,
     choose how many bedrooms you want to live in, and we will 
     give you a satisfactory answer about the price/sqft and number  
     of bathrooms!"),
  sidebarLayout(
    sidebarPanel(
      selectInput(
        "bedroom",
        label = "How many bedroom do you want to select ",
        choices = unique_bedrooms,
        selected = 2
      ) ,
      helpText("Note: dollars / sqft we used the price to divide with the 
               living area of house.")
      ),
    mainPanel(
      plotlyOutput("bathroom")
    )
  )
)

house_price_month <- house_sales %>%
  mutate(month = substr(date, 5, 6)) %>%
  mutate(months = as.factor(month)) 
unique_conditions <- sort(unique(house_price_month$condition))
unique_bedrooms <- sort(unique(house_price_month$bedrooms))
conditions_input <- selectInput(
  "conditions_input",
  label = "What is the condition for the house? ",
  choices = unique_conditions,
  selected = 3
)
bedrooms_input <- selectInput(
  "bedrooms_input",
  label = "How many bathrooms are in the house? ",
  choices = unique_bedrooms,
  selected = 3
)
limit_input <- sliderInput(
  inputId = "limit_input",
  label = "Price Range",
  max = 1050000,
  min = 70000,
  value = c(70000, 1050000)
)

page_three <- tabPanel(
  "Best Month",
  titlePanel("Relationship between month sold and price 
              when conditions and bathrooms are the same"),
  h5("Did you know selling prices vary by month?  
      Do you know when will be the best month to buy or sell a house? 
      Below is a box plot that shows the price differences by month.
      Please feel free to choose the condition of the house, the number
      of bathrooms, and the price range for houses.
     "),
  sidebarLayout(
    sidebarPanel(
      conditions_input,
      bedrooms_input,
      limit_input,
      helpText("Note: The condition means how good the condition of the
               house is overall with the higher number the better.")
    ),
    mainPanel(
      plotOutput("boxp")
    )
  )
)

page_four <- tabPanel(
  "Conclusion",
  titlePanel("Trends and Insights"),
  tags$h3("Seattle House Map"),
  tags$ul(
    tags$li("A noteable trend featured in the Seattle area was that increased living space tended to 
    congregate along the coast or surrounding lakes rather than in the heart of Seattle; this can
    be explained by bustling city life and urban neighborhoods featuring smaller apartment living 
    instead of houses. Consequently, housing with larger areas of living space are also more expensive."),
    tags$li("Broadmoar is the city with the greatest number of highly-rated housing; rating scores range from
            a 9 to 11. In addition, Broadmoar features housing with the largest areas of living space. 
            Therefore, there is some correlation between a house's area of living space and their rating score.
            From this correlation, it can be inferred that larger living spaces tends to create a higher 
            quality of life for the tenants."),
    tags$li("An obvious outlier found on the Seattle House Map is a house in Capitol Hill with a rating score of 
            13, a square footage of 12,050, and a $7,700,000 price tag.")),
  tags$h3("Bedroom Selection"),
  tags$ul(
    tags$li("It can be observed that the price per square feet for 1 bedroom
            is going to range around $399.30 per square feet, with a maximum 
            of 1 bathroom. This can be expected due to the fact that one bedrooms
            tend to contain a small number of tenants, and therefore only one bathroom
            is necessary."),
    tags$li("As the number of bedrooms increase, the price per square feet appears to
            decrease as the number of bathrooms reach approximately 2.5;
            this price decrease could insinuate an association with the housing type,
            in which apartments tend to be smaller with less bathrooms at a 
            higher cost. Likewise, the average detached home would feature more bathrooms (2.5) at a 
            large size, and therefore a smaller price per square footage."),
    tags$li("As you increase from 2.5 bathrooms, the price per square footage tends to 
            increase. After 2.5 bathrooms, the overall value per square footage of a home 
            is more affordable when there exists less bathrooms than bedrooms. There are likely other
            variables involved that explain this increase, such as featured amenities (gyms are typically 
            featured in apartment and townhouse neighborhoods), location, as well as the age of the house.")),
  tags$h3("Best Month"),
  tags$ul(
    tags$li("Comparing all combinations of condition and number of bathrooms, the median price of housing tends
            to be cheapest during the beginning (June) and end (September) of summer. In most conditions and 
            bathroom sizing, the months of summer showed the cheapest housing values. This can be explained by 
            family units moving locations after or before a school year begins."),
    tags$li("As the condition of the house increases, the average housing value also increases. For most bathrooms,
            the price of the housing doubles from condition 1 to condition 5. This shows that when the quality of housing
            is greater, the more costly the house will be sold for. "))
)

ui <- navbarPage(
  theme = shinytheme("flatly"),
  "House Selection",
  home_page,
  page_one,
  page_two,
  page_three,
  page_four,
  br(),
  hr(),
  p("INFO 201 | Spring 2019 | Amara Perry, George Ma, Lufei Wang, Lyons Lu, Mengru Zhou", align = "center"),
  p("Link to ", a("GitHub Repository", href = "https://github.com/Lyonsupernova/info201_Final_Project"), align = "center")
)

