library(dplyr)
library(shiny)
library(shinyWidgets)
library(shinythemes)
library(leaflet)
library(plotly)
house_sales <- read.csv("data/house_sales.csv", stringsAsFactors = FALSE)
# The page one's house preference depends on the frequency of bedroom bathroom
# combination. The most popular 30 bathroom bedroom combinations.

home_page <- tabPanel(
  "Home", 
  fluidRow(
    column(width = 12, img(src="banner.jpg", style = "display: block; margin-left: auto; margin-right: auto; width: 100%;"))
  ),
  tags$h3("Welcome"),
  p("Wecome! We are thrilled to have you with us! At this page, we will guide 
    you through to explore our webiste. We are an independent, non-commercial 
  set of tools and data that allows you to explore how housing market is in King
  County. We aim to help you to understand the specification of the house affect 
the housing price and to make better choices!"),
  tags$h3("About our Dataset"),
  p("Our target audience would be potential house buyers and renters. We focused
on the features that could have an impact on house sales prices. We draw data 
from the House Sales in King County and the dataset contains the house sale 
prices for King County between May 2014 to May 2015, it also contains 19 house
features. It is generated by Harlfoxem from public record."),
  h6(a("https://www.kaggle.com/harlfoxem/housesalesprediction",
       href = "https://www.kaggle.com/harlfoxem/housesalesprediction")),
  tags$h3("Getting Started"),
  p("Buying your first property is a major investment and can be a lucrative
    one, you could ask fundamental questions such as:"),
  p(em("- How many houses are there in my neighborhood and where are they?")),
  p(em("- How do different features of the house affect the price? (eg. number
  of bedrooms, years bulit, etc)")),
  p(em("- What is the sale history of the housing market in this neighborhood?"
  )),
  tags$h3("Technical Stuff"),
  p("We used Shiny App to build interactive web app straight from R. We also 
    used serval R pacakages to help format the application and wrangle the 
    data: "),
  p("- dplyr: to solve the data manipulation challenge"),
  p("- leaflet: to build our interactive map "),
  p("- ggolot2: to help create elegant and complex plots"),
  p("- shinythemes: to alter the overall appearance of Our Shiny application"),
  tags$h3("Contact Us"),
  p("W'd love to hear from you. Whether you thave a question about feature, 
    price, or anything else, our team is ready to answer all your questions!"),
  p("George Ma: zma9977@uw.edu "),
  p("lyons Lu: lyons2000124@outlook.com"),
  p("Mengru Zhou: vickyzhou9119@outlook.com"),
  p("Lufei Wang: lufeiw@uw.edu"),
  p("Amara Perry:amaraperry9@gmail.com")
)


house_preference <- house_sales %>% 
  mutate(price_per_square = price / sqft_living) %>% 
  group_by(bedrooms, bathrooms) %>% 
  summarise(price_per_square = round(mean(price_per_square), digits = 1),
            n = n()) %>% 
  arrange(-n) %>% 
  head(n = 30)
unique_bedrooms <- sort(unique(house_preference$bedrooms))
unique_bathrooms <- sort(unique(house_preference$bathrooms))
page_one <- tabPanel(
  "Bedroom Selection",
  titlePanel("Bedroom Selection"),
  h5("Do you know how many bathrooms would be the best choice for you to 
     select which types of house style you prefer. In the below select
     box, choose how many bedrooms you want to live in, and we will 
     give you a satisfactory answer about the price/sqft and bathroom 
     number!"),
  sidebarLayout(
    sidebarPanel(
      selectInput(
        "bedroom",
        label = "How many bedroom do you want to select ",
        choices = unique_bedrooms,
        selected = 2
      ) ,
      helpText("Note: dollars / sqft we used the price to divide with the 
               living area of house.")
      ),
    mainPanel(
      plotlyOutput("bathroom")
    )
  )
)
house_sales_small <- house_sales %>% 
  arrange(bedrooms) %>%
  filter(bedrooms < 2)
col_names2 <- colnames(house_sales_small)
x_input <- selectInput(
  inputId = "x_input",
  label = "select for x",
  choices = col_names2[c(6,7,12,15,20,21)]
)
page_two <- tabPanel(
  "Second Page",
  titlePanel("Scatter for all sales"),
  sidebarLayout(
    sidebarPanel(
      x_input  
    ),
    mainPanel(
      plotOutput("scatter")
    )
  )
)
page_three <- tabPanel(
  title = "Seattle's Map", 
  div(class="outer",tags$head(includeCSS("style.css")),
    leafletOutput("map", width = "100%", height = "100%"),
    absolutePanel(id = "controls", class = "panel panel-default", fixed = TRUE,
                  draggable = FALSE, top = 60, left = "auto", right = 20, 
                  bottom = "auto", width = "auto", height = "auto",
                  h3("Seattle Housing Sale History"),
                  p("Click on each data point to see more info"),
                  selectInput("color", "Color", c("Price" = "price",
                                                  "Condition" = "condition")),
                  selectInput("size", "Size", c("Don't show size" = "none",
                              "Area" = "sqft_living", "Rating" = "grade"))
    )
  )
)
ui <- navbarPage(
  theme = shinytheme("flatly"),
  "House Selection",
  home_page,
  page_one,
  page_two,
  page_three
)
